export const projects = [
  {
    id: 1,
    name: "Movie Seat Booking",
    path: "/movie-seat-booking",
    description: "A flexiable movie seat booking system",
    heightlight: ["LocalStorage", "Array Method", "FlexBox"],
    image: require("../../images/project-1.png"),
  },
  {
    id: 2,
    name: "Custom Video Player",
    path: "/custom-video-player",
    description: "A video player with HTML5 video API",
    heightlight: ["DOM selector", "MetaData", "setIntervel"],
    image: require("../../images/project-2.png"),
  },
  {
    id: 3,
    name: "Custom Video Player",
    path: "/custom-video-player",
    description: "A video player with HTML5 video API",
    heightlight: ["DOM selector", "MetaData"],
    image: require("../../images/project-3.png"),
  },
  {
    id: 4,
    name: "Custom Video Player",
    path: "/custom-video-player",
    description: "A video player with HTML5 video API",
    heightlight: ["DOM selector", "MetaData"],
    image: require("../../images/project-3.png"),
  },
  {
    id: 5,
    name: "Custom Video Player",
    path: "/custom-video-player",
    description: "A video player with HTML5 video API",
    heightlight: ["DOM selector", "MetaData"],
    image: require("../../images/project-3.png"),
  },
  {
    id: 6,
    name: "Custom Video Player",
    path: "/custom-video-player",
    description: "A video player with HTML5 video API",
    heightlight: ["DOM selector", "MetaData"],
    image: require("../../images/project-3.png"),
  },
]