export const projects = [
  {
    id: 1,
    name: "Movie Seat Booking",
    path: "/movie-seat-booking",
    description: "A flexiable movie seat booking system",
    heightlight: ["LocalStorage", "Array Method", "FlexBox"],
    image: require("../../images/project-1.png"),
  },
  {
    id: 2,
    name: "Custom Video Player",
    path: "/custom-video-player",
    description: "A video player with HTML5 video API",
    heightlight: ["DOM selector", "MetaData", "setIntervel"],
    image: require("../../images/project-2.png"),
  },
  {
    id: 3,
    name: "Exchange Rate Calculator",
    path: "/exchange-rate-calculator",
    description: "A video player with HTML5 video API",
    heightlight: ["DOM selector", "MetaData"],
    image: require("../../images/project-3.png"),
  },
  {
    id: 4,
    name: "Hangman Game",
    path: "/hangman-game",
    description: "A word guessing game",
    heightlight: ["SVG", "MetaData"],
    image: require("../../images/project-4.png"),
  },
  {
    id: 5,
    name: "Tomato Timer",
    path: "/tomato-timer",
    description: "A timer based on the tomato working scheme",
    heightlight: ["DOM selector", "MetaData"],
    image: require("../../images/project-5.png"),
  },
  {
    id: 6,
    name: "Meal Finder",
    path: "/meal-finder",
    description: "A recipe search engine",
    heightlight: ["API Comsumption", "Flex Box"],
    image: require("../../images/project-6.png"),
  },
  {
    id: 7,
    name: "Expense Tracker",
    path: "/expense-tracker",
    description: "A expense tracker App",
    heightlight: ["Array", "localStorage"],
    image: require("../../images/project-7.png"),
  },
  {
    id: 8,
    name: "Amiibo Explorer",
    path: "/amiibo-explorer",
    description: "amiibo explorer",
    heightlight: ["Redux", "API"],
    image: require("../../images/project-8.png"),
  },
  {
    id: 9,
    name: "Breakout Game",
    path: "/breakout-game",
    description: "A game on HTML 5 Canvas API",
    heightlight: ["HTML", "CSS"],
    image: require("../../images/project-9.png"),
  },
  {
    id: 10,
    name: "New Year Count Down",
    path: "/new-year-count-down",
    description: "A game on HTML 5 Canvas API",
    heightlight: ["HTML", "CSS"],
    image: require("../../images/project-10.png"),
  },
]
